### ISSUE TITLE
About download datasets

### ISSUE THREAD

**Issue by poweryin** [abhay97ps/Anomaly-Detection-in-Surveillance-Videos#1]
I try to download UCF-Crime datasets,but it is forbidden,"You don't have permission to access /cchen/UCF_Crimes.tar.gz on this server".Can I download the datasets in another way?

**Comment by adi-dhal** [comment]
You should ask Dr. Waqas Sultani who is the author of this study.

**Comment by AndyHon** [comment]
@poweryin Have you found the data set of UCF_CREME?
