### ISSUE TITLE
how did you convert video into vectors. I guess the code for that is missing.

### ISSUE THREAD

**Issue by himanshu16497** [abhay97ps/Anomaly-Detection-in-Surveillance-Videos#10]

**Comment by 1xabhay** [comment]
We use C3D (A 3D convolution network) to generate feature vectors on videos. C3D is pre-trained on sports1M dataset. Check this issue for outline [https://github.com/abhay97ps/Anomaly-Detection-in-Surveillance-Videos/issues/3#issuecomment-437678349](). Please also read the paper we have cited all neccesary details are clearly outlined in there.
