### ISSUE TITLE
Error in anomaly_NN.py 

### ISSUE THREAD

**Issue by anbuharry** [abhay97ps/Anomaly-Detection-in-Surveillance-Videos#21]
Hai,

![error_van](https://user-images.githubusercontent.com/54160097/126981247-0d1b6d40-873f-4a5b-bf8e-97f16fcbf89c.png)

Which kind of error is this and how can resolve it ?

Thanks

**Comment by Chuttyboy** [comment]
> Hai,
> 
> ![error_van](https://user-images.githubusercontent.com/54160097/126981247-0d1b6d40-873f-4a5b-bf8e-97f16fcbf89c.png)
> 
> Which kind of error is this and how can resolve it?
> 
> Thanks

@anbuharry @adi-dhal @abhay97ps 

Did you clear this error i too have same issue

**Comment by anbuharry** [comment]
> Hai,
> 
> ![error_van](https://user-images.githubusercontent.com/54160097/126981247-0d1b6d40-873f-4a5b-bf8e-97f16fcbf89c.png)
> 
> Which kind of error is this and how can resolve it ?
> 
> Thanks

indentation problem you need to use tab or space dont use two as same time
