### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by sarvang008** [abhay97ps/Anomaly-Detection-in-Surveillance-Videos#3]
Can you elaborate on the steps to run the project and dependencies needed.

**Comment by 1xabhay** [comment]
Hello, I apologise for such a late reply. 
The outline depends on why you are doing this project.
**Assuming you want a working model with not much intention to research and extend this, you can start with** 
1. downloading the data set. 
2. Data processing. 
3. Using C3D pre trained model on sport1m to extract features for your data set (I will not get into fine tuning under the assumption). 
4. Convert those feature using the MATLAB script provided by C3D into real valued data as per you requirement(make a csv for simple implementation). 
5. Code the architecture mentioned in the paper using you favourite deep learning library (tensorflow vs pytorch vs caffe2). 
6. Run it and report the results.

The necessary details about the hyper parameters and regularisation is all mentioned in the paper I have cited. Please read the paper and understand the idea first. Hope this helps

**Comment by Shiny128** [comment]
Hello 
I'm new to programming and I am unable to understand the execution steps to be followed to see the output . Please guide the sequence of execution in order to see the output

**Comment by nihalnurs** [comment]
Hello, 
Love your work here thanks so much, As @Shiny128 said, please help out the detail of what to run and execute to get the final result from training the model to predicting the anomaly.
thank you
