### ISSUE TITLE
About the result

### ISSUE THREAD

**Issue by demianzhang** [abhay97ps/Anomaly-Detection-in-Surveillance-Videos#5]
Thanks for your nice work. I want to know the final result comparing with the original paper. 
Look forwards for your reply.

**Comment by 1xabhay** [comment]
Our prediction accuracy was around 2-3% lower than the best mentioned in the paper. We actually used the architecture as a plug-in for testing purposes of our end to end video analysis system. The architecture though novel was not the best fit or our purposes so we moved on to a combination of i3d and yolo. Check that project out, it is work in progress https://github.com/adi-dhal/In_Depth_Video_Analysis

**Comment by AndyHon** [comment]
@abhay97ps I found your link has been invalid, may I ask if you can upload it again? https://github.com/adi-dhal/In_Depth_Video_Analysis
