### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by nadirlatif532** [abhay97ps/Anomaly-Detection-in-Surveillance-Videos#7]
Hope you are doing fine. 
I'm stuck at the feature extraction part. The whole 16 frame/32 segments thing is confusing me. could you please elaborate a bit more on that?

More specifically, if we are supposed to take 32 individual segments that are 16 frames each. from which part of the video will we take those segments from? 

any help regarding this will be really appreciated.

**Comment by nevinbaiju** [comment]
> We extract visual features from the fully connected (FC)
layer FC6 of the C3D network . Before computing fea-
tures, we re-size each video frame to 240 × 320 pixels and
fix the frame rate to 30 fps. We compute C3D features for
every 16-frame video clip followed by l 2 normalization. To
obtain features for a video segment, we take the average
of all 16-frame clip features within that segment.

I think the original work was done by fitting all the videos to 30fps and then the video was divided into 32 segments from which features were computed 16 frame by frame and then l2 normalized. I am not sure, just what I think is my understanding.

**Comment by adi-dhal** [comment]
Yes, the videos are first divided into 32 segments and then for each segment, every 16th frame is used to compute features. Description by @nevinbaiju is correct.
