### ISSUE TITLE
input_feature_vector_gen.py issue

### ISSUE THREAD

**Issue by nadirlatif532** [abhay97ps/Anomaly-Detection-in-Surveillance-Videos#9]
The script in unable to convert strings to float of my fc6-1 feature files in the following line:

`norm = normalize(np.array(map(float,open(os.path.join(dirpath, fl)).readlines()[0].strip().split(','))).reshape(1,-1),norm='l2')`

The error is specifically in the map function, it states, cannot convert strings to float.
Any help will be appreciated!

**Comment by adi-dhal** [comment]
Have you checked the output of the open function alone? Can you share what string, it tries to convert to float? As map function should work just fine.

**Comment by nadirlatif532** [comment]
Hey, Thanks for the response. here's the output of the open function:
`['\x01\x00\x00\x00\x00\x10\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\xa9\x0f\x0f@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe4\xb2;@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb0\xcc)=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00s]\xba@\xceE\xa4>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00{7_?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00V\xd0\xdb?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00Y\xcc\x85?\x00\x00\x00\x00T\xcf\xaf?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa0\xb3\xbf<\x00\x00\x00\x00\xf3=\xea?\x00\x00\x00\x00\x00\x00\x00\x00\xc3\x1b\x86@\x00\x00\x00\x00\x00\x00\x00\x00\x0cc\x93?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xd8\x0f\xc7>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00(\xc5\xa2?\x00\x00\x00\x00\x1c\x9co?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00x`\xdb>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x16\x0e\xb7?\xd3D\xb8?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfe\xffO@X', ']@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xaf\xa7y@\x00\x00\x00\x00\x1a\xfb\xaa?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00h\x08G>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00(_P>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x96\xc9\xfe?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfc+>\xc9\x96\x16@\x00\x00\x00\x00\x00\x00\x00\x00k\xe3\xc8?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00p\x813@\x82\x17\xc8>z\xc8+?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x87Dv?\x00\x00\x00\x00@\xf4G?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0b\x92l@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 S\xf6?\xf7\xd1S@\x00\x00\x00\x00\x10Bi?\x00\x00\x00\x00\x00\x00\x00\x00\x85<t?\x00\x00\x00\x008\xe7\x93=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00]\xe1\xee?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00&\xc0?\xc3\x1bg?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x90\x9c?\x00\x00\x00\x00}\xb1\x8c?\x00\x00\x00\x00\xbd5\xb0@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x90~\xef?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x8cx\x03@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x000m\xa5=\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00p|\x06@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00zS6?\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0eX\xae@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00h\xd0&>\x00\x00\x00\x00\x00\x00\x00\x00\xf3\x1c\xbc?\x00\x00\x00\x00\xa6\x81\x1b@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xba']`

**Comment by adi-dhal** [comment]
@nadirlatif532  Have you changed the fc6-1 feature into csv format with the matlab script provided in C3D repository( [https://docs.google.com/document/d/1-QqZ3JHd76JfimY4QKqOojcEaf5g3JS0lNh-FHTxLag/edit]()  use this guide to do so)?

Please follow [https://github.com/abhay97ps/Anomaly-Detection-in-Surveillance-Videos/issues/3#issuecomment-437678349]() for implementing the project.

**Comment by AndyHon** [comment]
@nadirlatif532 Could you please provide the data set of UCF_CREME?

**Comment by nadirlatif532** [comment]
The dataset is ~100GB. I currently don't have this kind of web storage capability. I can share the extracted features though?
